"""v2.8_v2.10_domain_model_update

Revision ID: a3f8f2356e1c
Revises: 20260409_0001
Create Date: 2026-04-23 12:43:46.801492
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a3f8f2356e1c'
down_revision = '20260409_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('RESPONSIBLE', 'CUSTOMER', 'OTHER', name='contact_role_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'OPERATOR', 'READER', name='unit_role_enum'), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'unit_id')
    )
    op.create_table('unit_policies',
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('operator_can_delete_protocol', sa.Boolean(), nullable=False),
    sa.Column('operator_can_move_protocol', sa.Boolean(), nullable=False),
    sa.Column('operator_can_lock_protocol', sa.Boolean(), nullable=False),
    sa.Column('operator_can_change_visibility', sa.Boolean(), nullable=False),
    sa.Column('operator_can_export_pdf', sa.Boolean(), nullable=False),
    sa.Column('reader_can_export_pdf', sa.Boolean(), nullable=False),
    sa.Column('reader_can_comment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('protocol_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('PROTOCOL', 'SAMPLE', 'PICTURE', name='comment_target_type_enum'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol_contacts',
    sa.Column('protocol_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['project_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('protocol_id', 'contact_id')
    )
    op.add_column('attachments', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('attachments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('attachments', sa.Column('extra_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('file_events', sa.Column('sha256', sa.Text(), nullable=True))
    op.add_column('microscope_pictures', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('microscope_pictures', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('microscope_pictures', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('microscope_pictures', sa.Column('extra_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.alter_column('navigation_images', 'caption',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('navigation_images', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('navigation_images', 'extra_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('optical_images', 'caption',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('optical_images', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('optical_images', 'extra_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('protocols', sa.Column('operator_id', sa.Uuid(), nullable=True))
    op.add_column('protocols', sa.Column('commissioned', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('protocols', sa.Column('project', sa.String(length=255), server_default='', nullable=False))
    op.add_column('protocols', sa.Column('introduction', sa.Text(), nullable=True))
    op.add_column('protocols', sa.Column('conclusion', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'protocols', 'operators', ['operator_id'], ['id'])
    op.alter_column('protocols', 'commissioned', server_default=None)
    op.alter_column('protocols', 'project', server_default=None)
    op.drop_column('protocols', 'yaml_customization')
    op.alter_column('videos', 'caption',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('videos', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('videos', 'extra_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'extra_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('videos', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('videos', 'caption',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('protocols', sa.Column('yaml_customization', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'protocols', type_='foreignkey')
    op.drop_column('protocols', 'conclusion')
    op.drop_column('protocols', 'introduction')
    op.drop_column('protocols', 'project')
    op.drop_column('protocols', 'commissioned')
    op.drop_column('protocols', 'operator_id')
    op.alter_column('optical_images', 'extra_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('optical_images', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('optical_images', 'caption',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('navigation_images', 'extra_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('navigation_images', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('navigation_images', 'caption',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('microscope_pictures', 'extra_info')
    op.drop_column('microscope_pictures', 'description')
    op.drop_column('microscope_pictures', 'caption')
    op.drop_column('microscope_pictures', 'embedding')
    op.drop_column('file_events', 'sha256')
    op.drop_column('attachments', 'extra_info')
    op.drop_column('attachments', 'description')
    op.drop_column('attachments', 'caption')
    op.drop_table('protocol_contacts')
    op.drop_table('comments')
    op.drop_table('unit_policies')
    op.drop_table('unit_memberships')
    op.drop_table('project_contacts')
    op.drop_table('operators')
    op.drop_table('units')
    # ### end Alembic commands ###
